export const REGISTER_FORM = 'REGISTER_FORM';
export const REGISTER_FORM_SUCCESS = 'REGISTER_FORM_SUCCESS';
export const REGISTER_FORM_FAIL = 'REGISTER_FORM_FAIL';

export const LOGIN_FORM = 'LOGIN_FORM';
export const LOGIN_FORM_SUCCESS = 'LOGIN_FORM_SUCCESS';
export const LOGIN_FORM_FAIL = 'LOGIN_FORM_FAIL';